# Используем базовый образ Python
FROM python:3.12.1-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY . .

RUN apk add --update --no-cache --virtual .tmp-build-deps \
    pip install --no-cache-dir -r requirements.txt