# Generated by Django 5.0.1 on 2024-01-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0007_serpuhovskayazones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushkinoZones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название игровой зоны')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('photo', models.ImageField(upload_to='photos/zones/')),
                ('photo_mobile', models.ImageField(upload_to='photos/zones/')),
                ('timeone', models.CharField(blank=True, max_length=255, verbose_name='Время 1 (Понедельник-Четверг)')),
                ('priceone', models.CharField(blank=True, max_length=255, verbose_name='Цена 1')),
                ('timetwo', models.CharField(blank=True, max_length=255, verbose_name='Время 2 (Понедельник-Четверг)')),
                ('prictwo', models.CharField(blank=True, max_length=255, verbose_name='Цена 2')),
                ('timetri', models.CharField(blank=True, max_length=255, verbose_name='Время 3 (Понедельник-Четверг)')),
                ('pricetri', models.CharField(blank=True, max_length=255, verbose_name='Цена 3')),
                ('timefour', models.CharField(blank=True, max_length=255, verbose_name='Время 4 (Понедельник-Четверг)')),
                ('pricefour', models.CharField(blank=True, max_length=255, verbose_name='Цена 4')),
                ('timefive', models.CharField(blank=True, max_length=255, verbose_name='Время 5 (Понедельник-Четверг)')),
                ('pricefive', models.CharField(blank=True, max_length=255, verbose_name='Цена 5')),
                ('timesix', models.CharField(blank=True, max_length=255, verbose_name='Время 6 (Понедельник-Четверг)')),
                ('pricesix', models.CharField(blank=True, max_length=255, verbose_name='Цена 6')),
                ('weekend_timeone', models.CharField(blank=True, max_length=255, verbose_name='Время 1 (Пятница-Воскресенье)')),
                ('weekend_priceone', models.CharField(blank=True, max_length=255, verbose_name='Цена 1')),
                ('weekend_timetwo', models.CharField(blank=True, max_length=255, verbose_name='Время 2 (Пятница-Воскресенье)')),
                ('weekend_prictwo', models.CharField(blank=True, max_length=255, verbose_name='Цена 2')),
                ('weekend_timetri', models.CharField(blank=True, max_length=255, verbose_name='Время 3 (Пятница-Воскресенье)')),
                ('weekend_pricetri', models.CharField(blank=True, max_length=255, verbose_name='Цена 3')),
                ('weekend_timefour', models.CharField(blank=True, max_length=255, verbose_name='Время 4 (Пятница-Воскресенье)')),
                ('weekend_pricefour', models.CharField(blank=True, max_length=255, verbose_name='Цена 4')),
                ('weekend_timefive', models.CharField(blank=True, max_length=255, verbose_name='Время 5 (Пятница-Воскресенье)')),
                ('weekend_pricefive', models.CharField(blank=True, max_length=255, verbose_name='Цена 5')),
                ('weekend_timesix', models.CharField(blank=True, max_length=255, verbose_name='Время 6 (Пятница-Воскресенье)')),
                ('weekend_pricesix', models.CharField(blank=True, max_length=255, verbose_name='Цена 6')),
                ('monitor_tile', models.CharField(blank=True, max_length=255, verbose_name='Монитор Заголовок или др...')),
                ('monitor', models.CharField(blank=True, max_length=255, verbose_name='Монитор(ы)')),
                ('processor_tile', models.CharField(blank=True, max_length=255, verbose_name='Процессор Заголовок или др...')),
                ('processor', models.CharField(blank=True, max_length=255, verbose_name='Процессор')),
                ('videocard_tile', models.CharField(blank=True, max_length=255, verbose_name='Видеокарта Заголовок или др...')),
                ('videocard', models.CharField(blank=True, max_length=255, verbose_name='Видеокарта')),
                ('ozu_tile', models.CharField(blank=True, max_length=255, verbose_name='Оперативная память Заголовок или др...')),
                ('ozu', models.CharField(blank=True, max_length=255, verbose_name='Оперативная память')),
                ('headset_tile', models.CharField(blank=True, max_length=255, verbose_name='Гарнитура Заголовок или др...')),
                ('headset', models.CharField(blank=True, max_length=255, verbose_name='Гарнитура')),
                ('keyboard_tile', models.CharField(blank=True, max_length=255, verbose_name='Клавиатура Заголовок или др...')),
                ('keyboard', models.CharField(blank=True, max_length=255, verbose_name='Клавиатура')),
                ('mouse_tile', models.CharField(blank=True, max_length=255, verbose_name='Мышь Заголовок или др...')),
                ('mouse', models.CharField(blank=True, max_length=255, verbose_name='Мышь')),
                ('sort', models.CharField(blank=True, max_length=4, verbose_name='Сортировка')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создание')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': '9) Пушкино Зоны (Клуб)',
                'verbose_name_plural': '9) Пушкино Игровые Зоны (Клуб)',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
