# Generated by Django 5.0.1 on 2024-02-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0011_clubpageseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoPageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='title seo')),
                ('description', models.TextField(blank=True, verbose_name='description seo')),
                ('keywords', models.TextField(blank=True, verbose_name='keywords seo')),
            ],
            options={
                'verbose_name': '0_2) SEO Акции page',
                'verbose_name_plural': '0_2) SEO Акции page',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='clubpageseo',
            options={'ordering': ['title'], 'verbose_name': '0_2) SEO Клубы page', 'verbose_name_plural': '0_2) SEO Клубы page'},
        ),
    ]
