# Generated by Django 5.0.1 on 2024-02-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0012_promopageseo_alter_clubpageseo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchisePageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='title seo')),
                ('description', models.TextField(blank=True, verbose_name='description seo')),
                ('keywords', models.TextField(blank=True, verbose_name='keywords seo')),
            ],
            options={
                'verbose_name': '0_4) SEO Франшиза',
                'verbose_name_plural': '0_4) SEO Франшиза',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='promopageseo',
            options={'ordering': ['title'], 'verbose_name': '0_3) SEO Акции', 'verbose_name_plural': '0_3) SEO Акции'},
        ),
    ]
