# Generated by Django 5.0.1 on 2024-02-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0013_franchisepageseo_alter_promopageseo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='title seo')),
                ('description', models.TextField(blank=True, verbose_name='description seo')),
                ('keywords', models.TextField(blank=True, verbose_name='keywords seo')),
            ],
            options={
                'verbose_name': '0_5) SEO Контакты',
                'verbose_name_plural': '0_5) SEO Контакты',
                'ordering': ['title'],
            },
        ),
    ]
