# Generated by Django 5.0.1 on 2024-02-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0016_vernadkaseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitinoSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='title seo')),
                ('description', models.TextField(blank=True, verbose_name='description seo')),
                ('keywords', models.TextField(blank=True, verbose_name='keywords seo')),
            ],
            options={
                'verbose_name': '0_8) SEO Митино',
                'verbose_name_plural': '0_8) SEO Митино',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='vernadkaseo',
            options={'ordering': ['title'], 'verbose_name': '0_7) SEO Вернадка', 'verbose_name_plural': '0_7) SEO Вернадка'},
        ),
    ]
