# Generated by Django 5.0.1 on 2024-02-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0019_zulebinoseo_alter_koptevoseo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZukovskySeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='title seo')),
                ('description', models.TextField(blank=True, verbose_name='description seo')),
                ('keywords', models.TextField(blank=True, verbose_name='keywords seo')),
            ],
            options={
                'verbose_name': '0_11) SEO Жуковский',
                'verbose_name_plural': '0_11) SEO Жуковский',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='zulebinoseo',
            options={'ordering': ['title'], 'verbose_name': '0_10) SEO Жулебино', 'verbose_name_plural': '0_10) SEO Жулебино'},
        ),
    ]
