# Generated by Django 5.0.1 on 2024-02-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0021_serpuhovkayaseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushkinoSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='title seo')),
                ('description', models.TextField(blank=True, verbose_name='description seo')),
                ('keywords', models.TextField(blank=True, verbose_name='keywords seo')),
            ],
            options={
                'verbose_name': '0_13) SEO Пушкино',
                'verbose_name_plural': '0_13 SEO Пушкино',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='serpuhovkayaseo',
            options={'ordering': ['title'], 'verbose_name': '0_12) SEO Серпуховская', 'verbose_name_plural': '0_12 SEO Серпуховская'},
        ),
    ]
