# Generated by Django 5.0.1 on 2024-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0023_mahachkalaseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/gallery/')),
                ('photo_mobile', models.ImageField(upload_to='photos/gallery/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': '_1) GALLERY_BOOTOM Главная',
                'verbose_name_plural': '0) GALLERY_BOOTOM Главная',
                'ordering': ['photo'],
            },
        ),
    ]
