# Generated by Django 5.0.1 on 2024-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0024_homegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='VdnhGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/gallery/')),
                ('photo_mobile', models.ImageField(upload_to='photos/gallery/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': '_2) GALLERY_BOOTOM ВДНХ',
                'verbose_name_plural': '_2) GALLERY_BOOTOM ВДНХ',
                'ordering': ['photo'],
            },
        ),
        migrations.AlterModelOptions(
            name='homegallery',
            options={'ordering': ['photo'], 'verbose_name': '_1) GALLERY_BOOTOM Главная', 'verbose_name_plural': '_1) GALLERY_BOOTOM Главная'},
        ),
    ]
