# Generated by Django 5.0.1 on 2024-02-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0025_vdnhgallery_alter_homegallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VernadkaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/gallery/')),
                ('photo_mobile', models.ImageField(upload_to='photos/gallery/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': '_3) GALLERY_BOOTOM Вернадка',
                'verbose_name_plural': '_3) GALLERY_BOOTOM Вернадка',
                'ordering': ['photo'],
            },
        ),
    ]
