# Generated by Django 5.0.1 on 2024-02-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0027_mitinogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerpuhovskayaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/gallery/')),
                ('photo_mobile', models.ImageField(upload_to='photos/gallery/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': '_5) GALLERY_BOOTOM Серпуховская',
                'verbose_name_plural': '_5) GALLERY_BOOTOM Серпуховская',
                'ordering': ['photo'],
            },
        ),
    ]
