# Generated by Django 5.0.1 on 2024-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0031_zukovskygallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushkinoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/gallery/')),
                ('photo_mobile', models.ImageField(upload_to='photos/gallery/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': '_9) GALLERY_BOOTOM Пушкино',
                'verbose_name_plural': '_9) GALLERY_BOOTOM Пушкино',
                'ordering': ['photo'],
            },
        ),
    ]
