# Generated by Django 5.0.1 on 2024-10-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0034_categorynewsnewvariant_mitinozonesnew_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MahachkalaPics',
            new_name='MahachkalaPicss',
        ),
    ]
