# Generated by Django 5.0.1 on 2024-10-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0035_rename_mahachkalapics_mahachkalapicss'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahachkalaPicssMahachkalaPicss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/mahachkalahpicwes/')),
                ('photo_mobile', models.ImageField(upload_to='photos/mahachkalahpics/')),
                ('sort', models.CharField(blank=True, max_length=4, verbose_name='Сортировка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eewewe', to='venom.mahachkalazones')),
            ],
            options={
                'verbose_name': '10) Картинки zones Махачкала',
                'verbose_name_plural': '10) Картинки zones Махачкала',
                'ordering': ['zone', 'id'],
            },
        ),
    ]
