# Generated by Django 5.0.1 on 2024-10-10 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0036_mahachkalapicssmahachkalapicss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahachkalapicss',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_picss', to='venom.mahachkalazones'),
        ),
    ]
