# Generated by Django 5.0.1 on 2024-10-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0037_alter_mahachkalapicss_zone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MahachkalaPicss',
        ),
    ]
