# Generated by Django 5.0.1 on 2024-10-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0038_delete_mahachkalapicss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MahachkalaPicssMahachkalaPicss',
        ),
    ]
