# Generated by Django 5.0.1 on 2024-10-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0041_mahachkalazoness'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageZonesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Серпуховская', 'Серпуховская'), ('ВДНХ', 'ВДНХ'), ('Вернадского', 'Вернадского'), ('Митино', 'Митино'), ('Коптево', 'Коптево'), ('Жулебино', 'Жулебино'), ('Жуковский', 'Жуковский')], max_length=211, verbose_name='Тип клуба')),
                ('image', models.ImageField(upload_to='contact_page_zones/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение зоны контактов',
                'verbose_name_plural': 'Изображения зон контактов',
            },
        ),
    ]
