# Generated by Django 5.0.1 on 2024-10-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0042_contactpagezonesimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagezonesimages',
            name='image_mobile',
            field=models.ImageField(default=1, upload_to='contact_page_zones/', verbose_name='Изображение для Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactpagezonesimages',
            name='image',
            field=models.ImageField(upload_to='contact_page_zones/', verbose_name='Изображение для Комп'),
        ),
    ]
