# Generated by Django 5.0.1 on 2024-10-12 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0043_contactpagezonesimages_image_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahachkalapicssmahachkalapicss',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eewewe', to='venom.mahachkalazoness'),
        ),
    ]
