# Generated by Django 5.0.1 on 2024-11-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0045_photovenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/tournament/', verbose_name='Фото')),
                ('photo_mobile', models.ImageField(upload_to='photos/tournament/', verbose_name='Фото мобильное')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Турниры VENOM',
                'verbose_name_plural': 'Турниры VENOM',
                'ordering': ['photo'],
            },
        ),
    ]
