# Generated by Django 5.0.1 on 2024-11-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0046_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название игровой зоны')),
                ('monitor', models.CharField(max_length=255, verbose_name='Монитор(ы)')),
                ('processor', models.CharField(max_length=255, verbose_name='Процессор')),
                ('video_card', models.CharField(max_length=255, verbose_name='Видеокарта')),
                ('photo', models.ImageField(upload_to='photos/zones/', verbose_name='Фото')),
                ('photo_mobile', models.ImageField(upload_to='photos/zones/', verbose_name='Фото мобильное')),
            ],
            options={
                'verbose_name': 'Игровая зона',
                'verbose_name_plural': 'Игровые зоны',
                'ordering': ['name'],
            },
        ),
    ]
