# Generated by Django 5.0.1 on 2024-11-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0047_zoneplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneplay',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
