# Generated by Django 5.0.1 on 2024-11-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0048_zoneplay_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoneplay',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='zoneplay',
            name='order',
        ),
        migrations.RemoveField(
            model_name='zoneplay',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='zoneplay',
            name='video_card',
        ),
        migrations.AlterField(
            model_name='zoneplay',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Характеристика')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venom.zoneplay', verbose_name='Игровая зона')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
    ]
