# Generated by Django 5.0.1 on 2024-11-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0050_zoneplay_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMahachkala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/mahachkala/', verbose_name='Фото')),
                ('photo_mobile', models.ImageField(upload_to='photos/mahachkala/', verbose_name='Фото мобильное')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фотогаллерея Махачкала',
                'verbose_name_plural': 'Фотогаллерея Махачкала',
                'ordering': ['photo'],
            },
        ),
        migrations.CreateModel(
            name='PhotoMitino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/mitino/', verbose_name='Фото')),
                ('photo_mobile', models.ImageField(upload_to='photos/mitino/', verbose_name='Фото мобильное')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фотогаллерея Митино',
                'verbose_name_plural': 'Фотогаллерея Митино',
                'ordering': ['photo'],
            },
        ),
        migrations.CreateModel(
            name='PhotoSerpuhskaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/serp/', verbose_name='Фото')),
                ('photo_mobile', models.ImageField(upload_to='photos/serp/', verbose_name='Фото мобильное')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фотогаллерея Серпуховская',
                'verbose_name_plural': 'Фотогаллерея Серпуховская',
                'ordering': ['photo'],
            },
        ),
        migrations.CreateModel(
            name='PhotoVdnx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/vdnx/', verbose_name='Фото')),
                ('photo_mobile', models.ImageField(upload_to='photos/vdnx/', verbose_name='Фото мобильное')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фотогаллерея ВДНХ',
                'verbose_name_plural': 'Фотогаллерея ВДНХ',
                'ordering': ['photo'],
            },
        ),
        migrations.CreateModel(
            name='PhotoVernadka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/vernadka/', verbose_name='Фото')),
                ('photo_mobile', models.ImageField(upload_to='photos/vernadka/', verbose_name='Фото мобильное')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фотогаллерея Вернадского',
                'verbose_name_plural': 'Фотогаллерея Вернадского',
                'ordering': ['photo'],
            },
        ),
    ]
