# Generated by Django 5.0.1 on 2024-11-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0051_photomahachkala_photomitino_photoserpuhskaya_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPageZonesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Серпуховская', 'Серпуховская'), ('ВДНХ', 'ВДНХ'), ('Вернадского', 'Вернадского'), ('Митино', 'Митино'), ('Коптево', 'Коптево'), ('Жулебино', 'Жулебино'), ('Жуковский', 'Жуковский'), ('Махачкала', 'Махачкала')], max_length=211, verbose_name='Тип клуба')),
                ('image', models.ImageField(upload_to='club_page_zones/', verbose_name='Изображение для Комп')),
                ('image_mobile', models.ImageField(upload_to='club_page_zones/', verbose_name='Изображение для Телефон')),
            ],
            options={
                'verbose_name': 'Изображение Клубы',
                'verbose_name_plural': 'Изображения Клубы',
            },
        ),
        migrations.AlterField(
            model_name='contactpagezonesimages',
            name='type',
            field=models.CharField(choices=[('Серпуховская', 'Серпуховская'), ('ВДНХ', 'ВДНХ'), ('Вернадского', 'Вернадского'), ('Митино', 'Митино'), ('Коптево', 'Коптево'), ('Жулебино', 'Жулебино'), ('Жуковский', 'Жуковский'), ('Махачкала', 'Махачкала')], max_length=211, verbose_name='Тип клуба'),
        ),
    ]
