# Generated by Django 5.0.1 on 2024-11-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0052_clubpagezonesimages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photomahachkala',
            options={'ordering': ['order'], 'verbose_name': 'Фотогаллерея Махачкала', 'verbose_name_plural': 'Фотогаллерея Махачкала'},
        ),
        migrations.AlterModelOptions(
            name='photomitino',
            options={'ordering': ['order'], 'verbose_name': 'Фотогаллерея Митино', 'verbose_name_plural': 'Фотогаллерея Митино'},
        ),
        migrations.AlterModelOptions(
            name='photovdnx',
            options={'ordering': ['order'], 'verbose_name': 'Фотогаллерея ВДНХ', 'verbose_name_plural': 'Фотогаллерея ВДНХ'},
        ),
        migrations.AlterModelOptions(
            name='photovenum',
            options={'ordering': ['order'], 'verbose_name': 'Фотогаллерея клубов VENOM', 'verbose_name_plural': 'Фотогаллерея клубов VENOM'},
        ),
        migrations.AlterModelOptions(
            name='photovernadka',
            options={'ordering': ['order'], 'verbose_name': 'Фотогаллерея Вернадского', 'verbose_name_plural': 'Фотогаллерея Вернадского'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['order'], 'verbose_name': 'Турниры VENOM', 'verbose_name_plural': 'Турниры VENOM'},
        ),
        migrations.AlterModelOptions(
            name='zoneplay',
            options={'ordering': ['order'], 'verbose_name': 'Игровая зона', 'verbose_name_plural': 'Игровые зоны'},
        ),
    ]
