# Generated by Django 5.0.1 on 2024-11-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0053_alter_photomahachkala_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahachkalazoness',
            options={'verbose_name': '10) Махачкала Зоны (Клуб)', 'verbose_name_plural': '10) Махачкала Игровые Зоны (Клуб)'},
        ),
    ]
