# Generated by Django 5.0.1 on 2024-11-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0054_alter_mahachkalazoness_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahachkalazoness',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сортировка'),
        ),
    ]
