# Generated by Django 5.0.1 on 2025-10-14 21:18

import django.db.models.deletion
import venom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0055_alter_mahachkalazoness_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название клуба')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='ClubGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=venom.models.club_gallery_upload_path)),
                ('photo_mobile', models.ImageField(upload_to=venom.models.club_gallery_upload_path)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='venom.club')),
            ],
            options={
                'verbose_name': 'Фото галереи (низ)',
                'verbose_name_plural': 'Фото галереи (низ)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClubNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('photo', models.ImageField(upload_to='photos/promo/')),
                ('photo_mobile', models.ImageField(upload_to='photos/promo/')),
                ('short', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('descr', models.TextField(blank=True, verbose_name='Текст')),
                ('sort', models.CharField(blank=True, max_length=4, verbose_name='Сортировка')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создание')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='venom.club')),
            ],
            options={
                'verbose_name': 'Новость Клуба',
                'verbose_name_plural': 'Новости Клуба',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='ClubPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('photo', models.ImageField(upload_to=venom.models.club_promo_upload_path)),
                ('photo_mobile', models.ImageField(blank=True, null=True, upload_to=venom.models.club_promo_upload_path)),
                ('short', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('descr', models.TextField(blank=True, verbose_name='Текст')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создание')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='venom.club')),
            ],
            options={
                'verbose_name': 'Акция клуба',
                'verbose_name_plural': 'Акции клуба',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='ClubSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='title seo')),
                ('description', models.TextField(blank=True, verbose_name='description seo')),
                ('keywords', models.TextField(blank=True, verbose_name='keywords seo')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='venom.club')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': "SEO's",
                'ordering': ['club__name'],
            },
        ),
        migrations.CreateModel(
            name='ClubZonesNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название игровой зоны')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('monitor_tile', models.CharField(blank=True, max_length=255, verbose_name='Монитор Заголовок или др...')),
                ('monitor', models.CharField(blank=True, max_length=255, verbose_name='Монитор(ы)')),
                ('processor_tile', models.CharField(blank=True, max_length=255, verbose_name='Процессор Заголовок или др...')),
                ('processor', models.CharField(blank=True, max_length=255, verbose_name='Процессор')),
                ('videocard_tile', models.CharField(blank=True, max_length=255, verbose_name='Видеокарта Заголовок или др...')),
                ('videocard', models.CharField(blank=True, max_length=255, verbose_name='Видеокарта')),
                ('ozu_tile', models.CharField(blank=True, max_length=255, verbose_name='Оперативная память Заголовок или др...')),
                ('ozu', models.CharField(blank=True, max_length=255, verbose_name='Оперативная память')),
                ('headset_tile', models.CharField(blank=True, max_length=255, verbose_name='Гарнитура Заголовок или др...')),
                ('headset', models.CharField(blank=True, max_length=255, verbose_name='Гарнитура')),
                ('keyboard_tile', models.CharField(blank=True, max_length=255, verbose_name='Клавиатура Заголовок или др...')),
                ('keyboard', models.CharField(blank=True, max_length=255, verbose_name='Клавиатура')),
                ('mouse_tile', models.CharField(blank=True, max_length=255, verbose_name='Мышь Заголовок или др...')),
                ('mouse', models.CharField(blank=True, max_length=255, verbose_name='Мышь')),
                ('timeone', models.CharField(blank=True, max_length=255, verbose_name='Время 1 (Понедельник-Четверг)')),
                ('priceone', models.CharField(blank=True, max_length=255, verbose_name='Цена 1')),
                ('timetwo', models.CharField(blank=True, max_length=255, verbose_name='Время 2 (Понедельник-Четверг)')),
                ('prictwo', models.CharField(blank=True, max_length=255, verbose_name='Цена 2')),
                ('timetri', models.CharField(blank=True, max_length=255, verbose_name='Время 3 (Понедельник-Четверг)')),
                ('pricetri', models.CharField(blank=True, max_length=255, verbose_name='Цена 3')),
                ('timefour', models.CharField(blank=True, max_length=255, verbose_name='Время 4 (Понедельник-Четверг)')),
                ('pricefour', models.CharField(blank=True, max_length=255, verbose_name='Цена 4')),
                ('timefive', models.CharField(blank=True, max_length=255, verbose_name='Время 5 (Понедельник-Четверг)')),
                ('pricefive', models.CharField(blank=True, max_length=255, verbose_name='Цена 5')),
                ('timesix', models.CharField(blank=True, max_length=255, verbose_name='Время 6 (Понедельник-Четверг)')),
                ('pricesix', models.CharField(blank=True, max_length=255, verbose_name='Цена 6')),
                ('weekend_timeone', models.CharField(blank=True, max_length=255, verbose_name='Время 1 (Пятница-Воскресенье)')),
                ('weekend_priceone', models.CharField(blank=True, max_length=255, verbose_name='Цена 1')),
                ('weekend_timetwo', models.CharField(blank=True, max_length=255, verbose_name='Время 2 (Пятница-Воскресенье)')),
                ('weekend_prictwo', models.CharField(blank=True, max_length=255, verbose_name='Цена 2')),
                ('weekend_timetri', models.CharField(blank=True, max_length=255, verbose_name='Время 3 (Пятница-Воскресенье)')),
                ('weekend_pricetri', models.CharField(blank=True, max_length=255, verbose_name='Цена 3')),
                ('weekend_timefour', models.CharField(blank=True, max_length=255, verbose_name='Время 4 (Пятница-Воскресенье)')),
                ('weekend_pricefour', models.CharField(blank=True, max_length=255, verbose_name='Цена 4')),
                ('weekend_timefive', models.CharField(blank=True, max_length=255, verbose_name='Время 5 (Пятница-Воскресенье)')),
                ('weekend_pricefive', models.CharField(blank=True, max_length=255, verbose_name='Цена 5')),
                ('weekend_timesix', models.CharField(blank=True, max_length=255, verbose_name='Время 6 (Пятница-Воскресенье)')),
                ('weekend_pricesix', models.CharField(blank=True, max_length=255, verbose_name='Цена 6')),
                ('sort', models.CharField(blank=True, max_length=4, verbose_name='Сортировка')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создание')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='venom.club')),
            ],
            options={
                'verbose_name': 'Зоны new',
                'verbose_name_plural': 'Игровые Зоны',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PhotoClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=venom.models.club_photo_upload_path, verbose_name='Фото')),
                ('photo_mobile', models.ImageField(upload_to=venom.models.club_photo_upload_path, verbose_name='Фото мобильное')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='venom.club')),
            ],
            options={
                'verbose_name': 'Фотогаллерея',
                'verbose_name_plural': 'Фотогаллереи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ZonesClubPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=venom.models.club_zone_pics_upload_path)),
                ('photo_mobile', models.ImageField(blank=True, null=True, upload_to=venom.models.club_zone_pics_upload_path)),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_photos', to='venom.club')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_pics', to='venom.clubzonesnew')),
            ],
            options={
                'verbose_name': 'Фото игровой зоны',
                'verbose_name_plural': 'Фото игровых зон',
                'ordering': ['zone', 'sort', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='clubnews',
            constraint=models.UniqueConstraint(fields=('club', 'slug'), name='unique_club_news_slug'),
        ),
        migrations.AddConstraint(
            model_name='clubpromo',
            constraint=models.UniqueConstraint(fields=('club', 'slug'), name='unique_club_promo_slug'),
        ),
    ]
