# Generated by Django 5.0.1 on 2025-10-15 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0056_club_clubgallery_clubnews_clubpromo_clubseo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Клуб', 'verbose_name_plural': 'Клубы'},
        ),
        migrations.CreateModel(
            name='NewsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(upload_to='photos/newsnew/')),
                ('photo_mobile', models.ImageField(upload_to='photos/newsnew/')),
                ('short', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('descr', models.TextField(blank=True, verbose_name='Текст')),
                ('sort', models.CharField(blank=True, max_length=4, verbose_name='Сортировка')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_main_page', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_news', to='venom.club', verbose_name='Клуб (если новость клубная)')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-time_create'],
            },
        ),
    ]
