# Generated by Django 5.0.1 on 2025-10-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0057_alter_club_options_newsnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/clubs/', verbose_name='Видео промо клуба (mp4)'),
        ),
    ]
