# Generated by Django 5.0.1 on 2025-10-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0058_club_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='pc_games',
            field=models.TextField(blank=True, verbose_name='Игры для ПК (через запятую, без пробелов)'),
        ),
        migrations.AddField(
            model_name='club',
            name='tv_games',
            field=models.TextField(blank=True, verbose_name='Игры для ТВ (через запятую, без пробелов)'),
        ),
    ]
