# Generated by Django 5.0.1 on 2025-10-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0059_club_pc_games_club_tv_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Как найти клуб', max_length=255, verbose_name='Заголовок блока')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес клуба')),
                ('landmark', models.CharField(blank=True, max_length=255, verbose_name='Ориентир')),
                ('metro_info', models.TextField(blank=True, verbose_name='Информация о метро (можно с переносами строк)')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон для связи')),
                ('lottie_file', models.FileField(blank=True, null=True, upload_to='lottie/clubs/', verbose_name='Lottie JSON-анимация')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать блок на сайте')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='venom.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Как найти клуб',
                'verbose_name_plural': 'Как найти клуб (блоки)',
            },
        ),
    ]
