# Generated by Django 5.0.1 on 2025-10-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0060_clubroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubBottomAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Заголовок')),
                ('txt', models.TextField(help_text='Можно использовать HTML-теги для форматирования', verbose_name='Текст')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_about', to='venom.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Нижние описание',
                'verbose_name_plural': 'Нижние описания',
            },
        ),
    ]
