# Generated by Django 5.0.1 on 2025-10-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0061_clubbottomabout'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clubzonesnew',
            constraint=models.UniqueConstraint(fields=('club', 'slug'), name='unique_zone_slug_per_club'),
        ),
    ]
