# Generated by Django 5.0.1 on 2025-10-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0062_clubzonesnew_unique_zone_slug_per_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubzonesnew',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='slug'),
        ),
    ]
