# Generated by Django 5.0.1 on 2025-10-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0063_alter_clubzonesnew_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='club_page_zones/', verbose_name='Изображение для компьютеров')),
                ('image_mobile', models.ImageField(upload_to='club_page_zones/', verbose_name='Изображение для телефонов')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zones_image', to='venom.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Изображение зон клуба',
                'verbose_name_plural': 'Изображения зон клубов',
            },
        ),
    ]
