# Generated by Django 5.0.1 on 2025-10-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0064_clubpageimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubzonesnew',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Зоны new', 'verbose_name_plural': 'Игровые Зоныы'},
        ),
        migrations.AddField(
            model_name='clubzonesnew',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
