# Generated by Django 5.0.1 on 2025-10-15 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0065_alter_clubzonesnew_options_clubzonesnew_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubzonesnew',
            options={'verbose_name': 'Игровая зона', 'verbose_name_plural': 'Игровые зоны'},
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='headset_tile',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='keyboard_tile',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='monitor_tile',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='mouse_tile',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='ozu_tile',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='pricefive',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='pricefour',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='priceone',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='pricesix',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='pricetri',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='prictwo',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='processor_tile',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='timefive',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='timefour',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='timeone',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='timesix',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='timetri',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='timetwo',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='videocard_tile',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='weekend_pricefive',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='weekend_pricefour',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='weekend_priceone',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='weekend_pricesix',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='weekend_pricetri',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='weekend_prictwo',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='weekend_timefive',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='weekend_timefour',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='weekend_timeone',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='weekend_timesix',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='weekend_timetri',
        ),
        migrations.RemoveField(
            model_name='clubzonesnew',
            name='weekend_timetwo',
        ),
        migrations.AlterField(
            model_name='clubzonesnew',
            name='monitor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Монитор'),
        ),
        migrations.CreateModel(
            name='ZonePriceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название блока (заголовок)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать блок')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_blocks', to='venom.clubzonesnew')),
            ],
            options={
                'verbose_name': 'Блок прайса',
                'verbose_name_plural': 'Блоки прайса',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ZonePriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255, verbose_name='Время')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='venom.zonepriceblock')),
            ],
            options={
                'verbose_name': 'Элемент прайса',
                'verbose_name_plural': 'Элементы прайса',
                'ordering': ['order'],
            },
        ),
    ]
