# Generated by Django 5.0.1 on 2025-10-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0066_alter_clubzonesnew_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubzonesnew',
            options={'verbose_name': 'Игровая зона', 'verbose_name_plural': 'Игровые зоныы'},
        ),
    ]
