# Generated by Django 5.0.1 on 2025-10-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0067_alter_clubzonesnew_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubroute',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес клуба'),
        ),
        migrations.AlterField(
            model_name='clubroute',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон для связи'),
        ),
        migrations.AlterField(
            model_name='clubroute',
            name='title',
            field=models.CharField(blank=True, default='Как найти клуб', max_length=255, verbose_name='Заголовок блока'),
        ),
    ]
