# Generated by Django 5.0.1 on 2025-10-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0068_alter_clubroute_address_alter_clubroute_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubzonesnew',
            options={'verbose_name': 'Игровая зона', 'verbose_name_plural': 'Игровые зоны'},
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер телефона'),
        ),
    ]
