# Generated by Django 5.0.1 on 2025-10-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0069_alter_clubzonesnew_options_club_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='map_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на карты'),
        ),
    ]
