# Generated by Django 5.0.1 on 2025-10-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0070_club_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_open_24',
            field=models.BooleanField(blank=True, null=True, verbose_name='Круглосуточный'),
        ),
    ]
