# Generated by Django 5.0.1 on 2025-10-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0071_club_is_open_24'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=64, verbose_name='Номер телефона')),
                ('video', models.FileField(upload_to='videos/mainpage/', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Главная странца',
                'verbose_name_plural': 'Главная странца',
            },
        ),
    ]
