# Generated by Django 5.0.1 on 2025-10-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0072_mainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchisePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=64, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Страница Франшизы',
                'verbose_name_plural': 'Страница Франшизы',
            },
        ),
    ]
