# Generated by Django 5.0.1 on 2025-10-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0073_franchisepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_logo', models.ImageField(upload_to='page_logo/', verbose_name='Картинка на вкладке')),
                ('site_logo', models.ImageField(upload_to='logo/', verbose_name='Картинка на странцие')),
            ],
        ),
    ]
