# Generated by Django 5.0.1 on 2025-10-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0074_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubzonesnew',
            options={'ordering': ['-count'], 'verbose_name': 'Игровая зона', 'verbose_name_plural': 'Игровые зоны'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Лого', 'verbose_name_plural': 'Лого'},
        ),
        migrations.AddField(
            model_name='club',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название клуба полное'),
        ),
        migrations.AddField(
            model_name='club',
            name='image_of_zones',
            field=models.ImageField(blank=True, null=True, upload_to='club_zones/', verbose_name='Картинка зон клуба'),
        ),
    ]
