# Generated by Django 5.0.1 on 2025-10-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0075_alter_clubzonesnew_options_alter_logo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoneplay',
            options={'ordering': ['order'], 'verbose_name': 'Игровая зона главной страницы', 'verbose_name_plural': 'Игровые зоны главной страницы'},
        ),
        migrations.RemoveField(
            model_name='newsnew',
            name='club',
        ),
        migrations.AddField(
            model_name='newsnew',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='global_news', to='venom.club', verbose_name='Клубы (если новость клубная)'),
        ),
    ]
