# Generated by Django 5.0.1 on 2025-10-18 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0076_alter_zoneplay_options_remove_newsnew_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPromoRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Связь клуба и акции',
                'verbose_name_plural': 'Связи клубов и акций',
            },
        ),
        migrations.AlterModelOptions(
            name='clubpromo',
            options={'ordering': ['-time_create'], 'verbose_name': 'Акция клуба', 'verbose_name_plural': 'Акции клубов'},
        ),
        migrations.AlterModelOptions(
            name='newsnew',
            options={'ordering': ['-time_create'], 'verbose_name': 'Новостьыыы', 'verbose_name_plural': 'Новостиыыы'},
        ),
        migrations.RemoveConstraint(
            model_name='clubpromo',
            name='unique_club_promo_slug',
        ),
        migrations.RemoveField(
            model_name='clubpromo',
            name='club',
        ),
        migrations.AlterField(
            model_name='clubpromo',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='clubpromo',
            name='photo',
            field=models.ImageField(upload_to='photos/clubs/promos/'),
        ),
        migrations.AlterField(
            model_name='clubpromo',
            name='photo_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='photos/clubs/promos/'),
        ),
        migrations.AlterField(
            model_name='clubpromo',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='clubpromorelation',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venom.club'),
        ),
        migrations.AddField(
            model_name='clubpromorelation',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venom.clubpromo'),
        ),
        migrations.AddField(
            model_name='clubpromo',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='promos', through='venom.ClubPromoRelation', to='venom.club', verbose_name='Клубы, участвующие в акции'),
        ),
        migrations.AddConstraint(
            model_name='clubpromorelation',
            constraint=models.UniqueConstraint(fields=('club', 'promo'), name='unique_club_promo_relation'),
        ),
    ]
