# Generated by Django 5.0.1 on 2025-10-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0077_clubpromorelation_alter_clubpromo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsnew',
            options={'ordering': ['-time_create'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='club',
            name='is_open',
            field=models.BooleanField(blank=True, null=True, verbose_name='Открыт ли клуб'),
        ),
    ]
