# Generated by Django 5.0.1 on 2025-10-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0078_alter_newsnew_options_club_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='is_open',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Открыт ли клуб'),
        ),
    ]
