# Generated by Django 5.0.1 on 2025-11-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0079_alter_club_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubzonesnew',
            name='is_tv',
            field=models.BooleanField(default=False, null=True, verbose_name='TV ZONE'),
        ),
    ]
