# Generated by Django 5.0.1 on 2025-11-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0080_clubzonesnew_is_tv'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsnew',
            name='show_tags',
            field=models.BooleanField(default=True, verbose_name='Показывать/скрывать теги'),
        ),
        migrations.AlterField(
            model_name='clubzonesnew',
            name='headset',
            field=models.CharField(blank=True, max_length=255, verbose_name='Гарнитура/Комфорт'),
        ),
        migrations.AlterField(
            model_name='clubzonesnew',
            name='keyboard',
            field=models.CharField(blank=True, max_length=255, verbose_name='Клавиатура/Преимущества'),
        ),
        migrations.AlterField(
            model_name='clubzonesnew',
            name='mouse',
            field=models.CharField(blank=True, max_length=255, verbose_name='Мышь/Расположение'),
        ),
        migrations.AlterField(
            model_name='clubzonesnew',
            name='ozu',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оперативная память/Звук'),
        ),
        migrations.AlterField(
            model_name='clubzonesnew',
            name='processor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Процессор/Телевизор'),
        ),
        migrations.AlterField(
            model_name='clubzonesnew',
            name='videocard',
            field=models.CharField(blank=True, max_length=255, verbose_name='Видеокарта/Размер и характеристики'),
        ),
    ]
