# Generated by Django 5.0.1 on 2025-11-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0081_newsnew_show_tags_alter_clubzonesnew_headset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonesclubpics',
            name='club',
        ),
        migrations.AlterField(
            model_name='newsnew',
            name='show_tags',
            field=models.BooleanField(default=True, verbose_name='Показывать теги'),
        ),
    ]
