# Generated by Django 5.0.1 on 2025-11-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0082_remove_zonesclubpics_club_alter_newsnew_show_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonesclubpics',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_photos', to='venom.club'),
        ),
    ]
