# Generated by Django 5.0.1 on 2025-11-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0083_zonesclubpics_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpromo',
            name='is_main_page',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AddField(
            model_name='clubpromo',
            name='show_tags',
            field=models.BooleanField(default=True, verbose_name='Показывать теги'),
        ),
    ]
