# Generated by Django 5.0.1 on 2025-11-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venom', '0084_clubpromo_is_main_page_clubpromo_show_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='background_video',
            field=models.FileField(null=True, upload_to='videos/mainpage/', verbose_name='Видео заднего фона'),
        ),
    ]
